# Generated by Django 3.2.9 on 2022-01-07 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crypto', '0001_initial'),
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Negotiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('C', 'Compra'), ('V', 'Venda'), ('S', 'Stake')], max_length=1)),
                ('valor_operacao', models.FloatField()),
                ('roi', models.FloatField(blank=True)),
                ('quantidade', models.FloatField()),
                ('data', models.DateField(default=datetime.date.today)),
                ('cryptomoeda', models.ManyToManyField(to='crypto.Crypto')),
                ('exchange', models.ManyToManyField(to='exchange.Exchange')),
            ],
        ),
    ]
