# Generated by Django 3.2.9 on 2022-01-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('palavra_passe', models.CharField(max_length=150)),
                ('usuario', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('anotacoes', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
