# Generated by Django 3.2.9 on 2022-01-07 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
        ('coinmarketcap', '0001_initial'),
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=10)),
                ('valor', models.FloatField(blank=True)),
                ('quantidade', models.FloatField(blank=True)),
                ('quantidade_investida', models.FloatField(blank=True)),
                ('objetivo', models.FloatField()),
                ('teste', models.IntegerField(default=1)),
                ('rede', models.CharField(max_length=100)),
                ('coinmarketcap', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='coinmarketcap.coinmarketcap')),
                ('exchange', models.ManyToManyField(to='exchange.Exchange')),
                ('wallet', models.ManyToManyField(blank=True, to='wallet.Wallet')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
