# Generated by Django 3.2.9 on 2022-01-26 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50)),
                ('sigla', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['sigla'],
            },
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='quantidade_investida',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='teste',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='valor',
        ),
        migrations.AddField(
            model_name='crypto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crypto.categoria'),
        ),
    ]
