# Generated by Django 3.2.9 on 2022-01-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_auto_20220126_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='objetivo',
            field=models.FloatField(null=True),
        ),
    ]
