# Generated by Django 3.2.9 on 2022-01-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinmarketcap', '0002_auto_20220108_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinmarketcap',
            name='circulating_supply',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coinmarketcap',
            name='initialized',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coinmarketcap',
            name='max_supply',
            field=models.IntegerField(default=0),
        ),
    ]
